In [1]:
import pandas as pd 
import numpy as np 
import tensorflow as tf 
from sklearn import model_selection

In [2]:
data=pd.read_excel("ENB2012_data.xlsx",0)
data.head()

X1     X2     X3      X4   X5  X6   X7  X8     Y1     Y2
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55  21.33
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55  21.33
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55  21.33
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55  21.33
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84  28.28

In [3]:
data.shape

(768, 10)

In [4]:
data=data.drop(columns="Y2")
data.head()

X1     X2     X3      X4   X5  X6   X7  X8     Y1
0  0.98  514.5  294.0  110.25  7.0   2  0.0   0  15.55
1  0.98  514.5  294.0  110.25  7.0   3  0.0   0  15.55
2  0.98  514.5  294.0  110.25  7.0   4  0.0   0  15.55
3  0.98  514.5  294.0  110.25  7.0   5  0.0   0  15.55
4  0.90  563.5  318.5  122.50  7.0   2  0.0   0  20.84

In [5]:
y=data[["Y1"]]
y

Y1
0    15.55
1    15.55
2    15.55
3    15.55
4    20.84
..     ...
763  17.88
764  16.54
765  16.44
766  16.48
767  16.64

[768 rows x 1 columns]

In [6]:
x=data.drop(columns="Y1")
x

X1     X2     X3      X4   X5  X6   X7  X8
0    0.98  514.5  294.0  110.25  7.0   2  0.0   0
1    0.98  514.5  294.0  110.25  7.0   3  0.0   0
2    0.98  514.5  294.0  110.25  7.0   4  0.0   0
3    0.98  514.5  294.0  110.25  7.0   5  0.0   0
4    0.90  563.5  318.5  122.50  7.0   2  0.0   0
..    ...    ...    ...     ...  ...  ..  ...  ..
763  0.64  784.0  343.0  220.50  3.5   5  0.4   5
764  0.62  808.5  367.5  220.50  3.5   2  0.4   5
765  0.62  808.5  367.5  220.50  3.5   3  0.4   5
766  0.62  808.5  367.5  220.50  3.5   4  0.4   5
767  0.62  808.5  367.5  220.50  3.5   5  0.4   5

[768 rows x 8 columns]

In [7]:
X=x.to_numpy()
X

array([[9.800e-01, 5.145e+02, 2.940e+02, ..., 2.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 3.000e+00, 0.000e+00,
        0.000e+00],
       [9.800e-01, 5.145e+02, 2.940e+02, ..., 4.000e+00, 0.000e+00,
        0.000e+00],
       ...,
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 3.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 4.000e+00, 4.000e-01,
        5.000e+00],
       [6.200e-01, 8.085e+02, 3.675e+02, ..., 5.000e+00, 4.000e-01,
        5.000e+00]])

In [8]:
Y=y.to_numpy()
Y

array([[15.55 ],
       [15.55 ],
       [15.55 ],
       [15.55 ],
       [20.84 ],
       [21.46 ],
       [20.71 ],
       [19.68 ],
       [19.5  ],
       [19.95 ],
       [19.34 ],
       [18.31 ],
       [17.05 ],
       [17.41 ],
       [16.95 ],
       [15.98 ],
       [28.52 ],
       [29.9  ],
       [29.63 ],
       [28.75 ],
       [24.77 ],
       [23.93 ],
       [24.77 ],
       [23.93 ],
       [ 6.07 ],
       [ 6.05 ],
       [ 6.01 ],
       [ 6.04 ],
       [ 6.37 ],
       [ 6.4  ],
       [ 6.366],
       [ 6.4  ],
       [ 6.85 ],
       [ 6.79 ],
       [ 6.77 ],
       [ 6.81 ],
       [ 7.18 ],
       [ 7.1  ],
       [ 7.1  ],
       [ 7.1  ],
       [10.85 ],
       [10.54 ],
       [10.77 ],
       [10.56 ],
       [ 8.6  ],
       [ 8.49 ],
       [ 8.45 ],
       [ 8.5  ],
       [24.58 ],
       [24.63 ],
       [24.63 ],
       [24.59 ],
       [29.03 ],
       [29.87 ],
       [29.14 ],
       [28.09 ],
       [26.28 ],
       [26.91 ],
       [26.37 

# model building 

In [9]:
trainx,trainy,testx,testy=model_selection.train_test_split(X,Y,train_size=.70,random_state=3)

In [178]:
epoch=10
batch_size=70

In [179]:
model1=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(),
    tf.keras.layers.Dense(512,activation=tf.nn.relu),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(256,activation=tf.nn.relu),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(128,activation=tf.nn.log_softmax),
    tf.keras.layers.Dropout(.2),
    tf.keras.layers.Dense(1,activation='linear')])

In [188]:
optimiser=tf.keras.optimizers.Adam()
model1.compile(optimizer=optimiser,loss=tf.keras.losses.huber,metrics=tf.keras.metrics.mean_absolute_error)

In [189]:
model1.fit(trainx,testx,batch_size=70,epochs=5)

Epoch 1/5
8/8 [==============================] - 0s 8ms/step - loss: 5.7219 - mean_absolute_error: 6.2041
Epoch 2/5
8/8 [==============================] - 0s 8ms/step - loss: 5.2562 - mean_absolute_error: 5.7308
Epoch 3/5
8/8 [==============================] - 0s 8ms/step - loss: 5.3189 - mean_absolute_error: 5.8001
Epoch 4/5
8/8 [==============================] - 0s 6ms/step - loss: 5.3011 - mean_absolute_error: 5.7765
Epoch 5/5
8/8 [==============================] - 0s 6ms/step - loss: 5.3322 - mean_absolute_error: 5.8109


In [190]:
model1.evaluate(trainy, testy)

8/8 [==============================] - 0s 3ms/step - loss: 3.2826 - mean_absolute_error: 3.7632


[3.282616138458252, 3.7632453441619873]

In [191]:
model1.predict(trainy)

array([[26.543594 ],
       [13.994642 ],
       [13.710858 ],
       [26.761175 ],
       [13.710858 ],
       [26.762753 ],
       [26.719023 ],
       [13.989318 ],
       [20.59115  ],
       [14.148512 ],
       [27.43562  ],
       [13.710858 ],
       [27.65228  ],
       [24.353136 ],
       [13.710858 ],
       [13.710858 ],
       [13.710858 ],
       [27.330656 ],
       [36.34451  ],
       [13.710858 ],
       [13.710858 ],
       [13.974192 ],
       [26.576597 ],
       [27.346394 ],
       [26.947865 ],
       [13.710858 ],
       [13.710858 ],
       [36.515545 ],
       [21.408134 ],
       [24.270552 ],
       [28.015745 ],
       [13.710858 ],
       [27.057116 ],
       [21.098314 ],
       [26.879938 ],
       [14.0334015],
       [26.913036 ],
       [24.171164 ],
       [23.987757 ],
       [14.168675 ],
       [13.885287 ],
       [26.828924 ],
       [26.459652 ],
       [13.710858 ],
       [35.97594  ],
       [27.624243 ],
       [15.43644  ],
       [27.86